config/routes.rb
Hello::Application.routes.draw do
  root 'helloworlds#index'
  
  resources :helloworlds

end

app/models/helloworld.rb
class Helloworld < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/helloworlds_controller.rb
class HelloworldsController < ApplicationController
	def index
		@helloworlds = Helloworld.all
	end
	
	def new
		@helloworld = Helloworld.new
	end
	
	def create
		@helloworld = Helloworld.create(helloworld_params)
		redirect_to root_path
	end
	
	private
	
	def helloworld_params
		params.require(:helloworld).permit(:language, :greeting)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/helloworld_helper.rb
module HelloworldHelper
end

app/helpers/helloworlds_helper.rb
module HelloworldsHelper
end

app/views/countries/index.html.erb
<h1> Hello World </h1>

app/views/helloworld/index.html.erb
<h1> Hello World in different languages</h1>

<h3> 
	<% @helloworlds.each do |h| %>
		<%= h.language %>
		<%= h.greeting %>
	<%end%>
	<p> click here to enter hello world in your language 
		<%= link_to 'here', new_helloworld_path %>
	</p>
</h3>

app/views/helloworld/new.html.erb
<div>
	<h1> Add hello world in your language </h1>
	<%= simple_form_for (@helloworld) do |f| %>
		<%= f.input :language %>
		<%= f.input :greeting %>
		<%= f.submit 'Create' %>
	<% end %>
</div>

app/views/helloworlds/index.html.erb
<h1> Hello World in different languages</h1>

<h3> 
	<% @helloworlds.each do |h| %>
		<%= h.language %>
		<%= h.greeting %> </br> </br>
	<%end%>
	<p> click here to enter hello world in your language 
		<%= link_to 'here', new_helloworld_path %>
	</p>
</h3>

app/views/helloworlds/new.html.erb
<div>
	<h1> Add hello world in your language </h1>
	<%= simple_form_for (@helloworld) do |f| %>
		<%= f.input :language %>
		<%= f.input :greeting %>
		<%= f.submit 'Create' %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hello</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>